### ISSUE TITLE
Set up support of TypeScript

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1285]
- [x] Declare TypeScript language, properties #1288
- [x] TypeScript sensor, use existing server running on Node to parse TypeScript files, report parsing errors #1289
- [x] Declare a eslint-based rule (we can reuse rule existing in JS, e.g. https://jira.sonarsource.com/browse/RSPEC-4126 "no-all-duplicated-branches"), rely on annotation to know in which languages the rule should be declared (like in cfamily). Set up ruling with TS files. Compare results from SonarTS rule implementation and a current one #1294
- [x] Declare profiles for TS #1296
- [ ] Contextual sensor for TypeScript (for SonarLint support), implies creation of language service #1302
- [x] Metrics etc. (can be implemented only for TS, but if it makes sense to calculate them for JS as well, we can go for it)
   - [x] CPD #1303
   - [x] ncloc lines, commentLines, nosonarLines, executableLines, functions number,  statements number, classes number #1304
   - [x] cyclomatic complexity #1305
   - [x] cognitive complexity #1326
   - [x] syntax highlighting #1306
   - [x] symbol highlighting (!) #1307
- [x] import of TSLint report #1286
- [x] import of coverage report (deprecate typescript property) #1287
- [x] Declare a eslint-based rule using TypeChecker, e.g. `@typescript-eslint/no-unnecessary-type-assertion` (https://jira.sonarsource.com/browse/RSPEC-4325) #1308

To Dogfood on Peach:
* create dogfood branch on SonarTS with empty plugin (it will be deployed on Peach but not Next as Next is using Dev (master) version of SonarTS)
* create dogfood on SonarJS which will declare TS language, this will be deployed on Peach

Create a long-live branch `dogfood/mmf-1775` which will "replace" master in this sprint. Every new PR should be based on it.

**Comment by saberduck** [comment]
@vilchik-elena I think we can close this issue?
