### ISSUE TITLE
Rely on existing ESLint rules to analyze TypeScript

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1293]
Iteration 7 (fri):
- [x] Add rule S4139 (based on '@typescript-eslint/no-for-in-array') for TS #1466
- [x] Add rules S4140 (based on 'no-sparse-arrays') for TS/JS (new rule for JS) #1468
- [x] Add rule S4143 (based on 'eslint-plugin-sonarjs/no-element-overwrite') for TS #1469 
- [x] Add rule S4137 (based on '@typescript-eslint/consistent-type-assertions') for TS #1463
- [x] Add rule S3512 (based on 'prefer-template') for TS/JS #1449
- [x] Add rule S3533 (based on '@typescript-eslint/no-require-imports') for TS #1450
- [x] Add rule S4124 (based on '@typescript-eslint/no-misused-new') for TS #1461
- [x] Add rule S4136 (based on '@typescript-eslint/adjacent-overload-signatures') for TS #1462

Iteration 6 (thus):
- [x] Add rule S4326 (based on 'no-return-await') for TS/JS #1474
- [x] Add rule S4327 (based on '@typescript-eslint/no-this-alias') for TS #1475
- [x] Add rule S3696 (based on 'no-throw-literal') for TS/JS (new rule for JS) #1451
- [x] Add rule S3699 (based on 'eslint-plugin-sonarjs/no-use-of-empty-return-value') for TS #1452
- [x] Add rule S3786 (based on 'no-template-curly-in-string') for TS/JS #1455
- [x] Add rule S3799 (based on 'no-empty-pattern') for TS/JS #1456
- [x] Add rule S3854 (based on 'constructor-super') for TS/JS #1458
- [x] Add rule S3863 (based on 'no-duplicate-imports') #1459
- [x] Add rule S4023 (based on '@typescript-eslint/no-empty-interface') for TS #1460
- [x] Add rule S3353 (based on 'prefer-const') for TS/JS #1445

Iteration 5 (wed):
- [x] Add rule S2688 (based on 'use-isnan') for TS/JS #1436
- [x] Add rule S2737 (based on 'eslint-plugin-sonarjs/no-useless-catch') for TS #1437
- [x] Add rule S2814 (based on 'no-redeclare') for TS/JS #1438
- [x] Add rule S2933 (based on '@typescript-eslint/prefer-readonly') for TS #1441
- [x] Add rule S2966 (based '@typescript-eslint/no-non-null-assertion') for TS #1443 
- [x] Add rule S3402 (based on @typescript-eslint/restrict-plus-operands) #1446
- [x] Add rule S3498 (based on 'object-shorthand') for TS/JS #1447 
- [x] Add rule S4204 (based on '@typescript-eslint/no-explicit-any') for TS #1473
- [x] Add rule S4144 (based on 'eslint-plugin-sonarjs/no-identical-functions') for TS #1470
- [x] Add rule S4156 (based on '@typescript-eslint/prefer-namespace-keyword') for TS #1471
- [x] Add rule S4138 (based on '@typescript-eslint/prefer-for-of') for TS #1465

Iteration 4 (tue):
- [x] Add rule S1526 (based on `no-use-before-define`) for TS/JS #1419
- [x] Add rule S1656 (based on 'no-self-assign') for TS/JS #1427
- [x] Add rule S1764 (based on 'eslint-plugin-sonarjs/no-identical-expressions') for TS #1429
- [x] Add rule S1862 (based on 'eslint-plugin-sonarjs/no-identical-conditions') for TS #1430
- [x] Add rule S1871 (based on 'eslint-plugin-sonarjs/no-duplicated-branches') for TS #1431
- [x] Add rule S1940 (based on 'eslint-plugin-sonarjs/no-inverted-boolean-check') for TS #1433
- [x] Add rule S2228 (based on 'no-console') for TS/JS #1434
- [x] Add rule S2685 (based on 'no-caller') for TS/JS #1435
- [x] Add rule S3504 (based on 'no-var') for TS/JS #1448
- [x] Add rule S3257 (based on '@typescript-eslint/no-inferrable-types') for TS #1444

Iteration 3:
- [x] Add S122 (based on `max-statements-per-line`) :exclamation: compare rules scopes before implementing
- [x] Add S1105 (based on `brace-style`) #1404
- [x] Add S1264 (based on `eslint-plugin-sonarjs/prefer-while`) for TS #1409
- [x] Add S1440 (basen on `eqeqeq`) for TS/JS #1410
- [x] Add S1488 (based on `eslint-plugin-sonarjs/prefer-immediate-return`) for TS #1413
- [x] Add S1516 (based on `no-multi-str`) for TS/JS #1415
- [x] Add S1523 (based on `no-eval`) for TS #1416
- [x] Add rule S1117 (former S1524) (based on `no-shadow`) for TS/JS #1417
- [x] Add rule S1525 (based on `no-debugger`) for TS/JS #1418

Iteration 2:
- [x] Add S138  (based on 'max-lines-per-function') (see #639) #1367
- [x] Add S905 (based on 'no-unused-expressions') #1368
- [x] Add S1125 (based on 'eslint-plugin-sonarjs/no-redundant-boolean') #1369
- [x] Add S1143 (based on 'no-unsafe-finally') #1370
- [x] Add S1192 (based on 'eslint-plugin-sonarjs/no-duplicate-string') #1371
- [x] Add S1301 (based on 'eslint-plugin-sonarjs/no-small-switch') #1372
- [x] Add S1438 (based on '@typescript-eslint/semi') (can we use 'semi' from eslint-core?) #1373
- [x] Add S1441 (based on 'quotes') #1375
- [x] Add S1479 (based on 'eslint-plugin-sonarjs/max-switch-cases') #1376
- [x] Add S121 (based on 'curly') #1396

Iteration 1:
- [x] max-line-length S103 `max-len` (eslint core) #1337
- [x] max-file-line-count | S104  | `max-lines` (eslint core) #1338
- [x] max-params | S107 | `max-params` (eslint core) #1339
- [x] no-empty-nested-blocks S108 `no-empty` (eslint core with `"allowEmptyCatch": true`) #1340 
- [x] no-magic-numbers S109 | `no-magic-numbers` (eslint core) #1341 
- [x] eofline S113 `eol-last` (eslint core) #1343
- [x] ban-comma-operator S878 `no-sequences` (eslint core) #1344
- [x] no-collapsible-if S1066 `eslint-plugin-sonarjs/no-collapsible-if` #1345
- [x] no-extra-semicolon S1116 `no-extra-semi` (eslint core) #1346
