### ISSUE TITLE
Migrate remaining rules from Java frontend to ESLint based frontend

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#1754]
Following rules need to be migrated to the ESLint based frontend. Once finished we can remove Java based frontend completely #1755 .
Corresponding MMF https://jira.sonarsource.com/browse/MMF-1521

- [ ] RSPEC-128 "Switch cases should end with an unconditional "break" statement" -> https://eslint.org/docs/rules/no-fallthrough
- [ ] RSPEC-131 ""switch" statements should have "default" clauses" -> https://eslint.org/docs/rules/default-case
- [ ] RSPEC-1119 "Labels should not be used" -> https://eslint.org/docs/rules/no-labels
- [ ] RSPEC-1186 "Functions should not be empty" -> https://eslint.org/docs/rules/no-empty-function
- [ ] RSPEC-1321 ""with" statements should not be used" -> https://eslint.org/docs/rules/no-with
- [ ] RSPEC-1481 "Unused local variables should be removed" -> https://eslint.org/docs/rules/no-unused-var
- [ ] RSPEC-1534 "Property names should not be duplicated within a class or object literal" -> https://eslint.org/docs/rules/no-dupe-keys
- [ ] RSPEC-1536 "Function argument names should be unique" -> https://eslint.org/docs/rules/no-dupe-args
- [ ] RSPEC-1763 "Jump statements should not be followed by dead code" -> https://eslint.org/docs/rules/no-unreachable
- [ ] RSPEC-2189 "Loops should not be infinite" -> https://eslint.org/docs/rules/no-unmodified-loop-condition
- [ ] RSPEC-2251 "A "for" loop update clause should move the counter in the right direction" -> https://eslint.org/docs/rules/for-direction
- [ ] RSPEC-2376 "Property getters and setters should come in pairs" -> https://eslint.org/docs/rules/accessor-pairs
- [ ] RSPEC-2703 "Variables should be declared explicitly" -> https://eslint.org/docs/rules/no-undef
- [ ] RSPEC-2990 "The global "this" object should not be used" -> https://eslint.org/docs/rules/no-invalid-this
- [ ] RSPEC-3001 ""delete" should be used only with object properties" -> https://eslint.org/docs/rules/no-delete-var
- [ ] RSPEC-3358 "Ternary operators should not be nested" -> https://eslint.org/docs/rules/no-nested-ternary
- [ ] RSPEC-3500 "Attempts should not be made to update "const" variables" -> https://eslint.org/docs/rules/no-const-assign
- [ ] RSPEC-3531 "Generators should "yield" something" -> https://eslint.org/docs/rules/require-yield
- [ ] RSPEC-3796 "Callbacks of array methods should have return statements" -> https://eslint.org/docs/rules/array-callback-return
- [ ] RSPEC-3812 "Results of "in" and "instanceof" should be negated rather than operands" -> https://eslint.org/docs/rules/no-unsafe-negation
- [ ] RSPEC-3834 ""Symbol" should not be used as a constructor" -> https://eslint.org/docs/rules/no-new-symbol
- [ ] RSPEC-3854 ""super()" should be invoked appropriately" -> https://eslint.org/docs/rules/constructor-super, https://eslint.org/docs/rules/no-this-before-super  two rules in eslint
- [ ] RSPEC-1528 "Array constructors should not be used" -> https://eslint.org/docs/rules/no-array-constructor
- [ ] RSPEC-2138 ""undefined" should not be assigned" -> https://eslint.org/docs/rules/no-undef-init
- [ ] RSPEC-2424 "Built-in objects should not be overridden" -> https://eslint.org/docs/rules/no-redeclare
- [ ] RSPEC-3735 ""void" should not be used" -> https://eslint.org/docs/rules/no-void
- [ ] RSPEC-3863 "Imports from the same modules should be merged" -> https://eslint.org/docs/rules/no-duplicate-imports
- [ ] RSPEC-139 https://eslint.org/docs/rules/line-comment-position
- [ ] RSPEC-909 https://eslint.org/docs/rules/no-continue
- [ ] RSPEC-1131 https://eslint.org/docs/rules/no-trailing-spaces
- [ ] RSPEC-1314 https://eslint.org/docs/rules/no-octal
- [ ] RSPEC-1535 https://eslint.org/docs/rules/guard-for-in
- [ ] RSPEC-1537 https://eslint.org/docs/rules/comma-dangle
- [ ] RSPEC-1774 https://eslint.org/docs/rules/no-ternary
- [ ] RSPEC-1788 https://eslint.org/docs/rules/default-param-last.
- [ ] RSPEC-3523 https://eslint.org/docs/rules/no-new-func

**Comment by EJLearner** [comment]
Is there an estimate for when this will be completed? Our project is adopting the usage of optional chaining and are getting more errors in the sonar scanner log. 

My understanding is that these errors will occur until this issue is closed.

**Comment by vilchik-elena** [comment]
@EJLearner parsing errors from old frontend are logged in debug only, so you would not see them by default. Are you sure your parsing errors are not caused by new frontend? 
I would recommend create a new issue and discuss it there

**Comment by rbanks54** [comment]
Just curious if there's been any movement on this?

**Comment by vilchik-elena** [comment]
@rbanks54 nope

**Comment by saberduck** [comment]
replaced by #1918
